In [47]:
import nltk
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix 

In [48]:
data = pd.read_csv("processed_data.csv")
data

Title  \
0     تيرتل تري لابز للتقنيات الحيويه تحصل علي تمويل...   
1        تعد دراسه الجدوي لمشروعك الناشء 6 عوامل اساسيه   
2     منح جاءزه نوبل الطب لاكتشاف مجال التهاب الكبد ...   
3     هيءه الغذاء والدواء الامريكيه لقاح مودرنا حقق ...   
4     حظر بروتين الجهاز المناعي يساعد علي محاربه عدو...   
...                                                 ...   
8394  قواعد اوروبيه تهدد بخفض 10 ايرادات شركات التكن...   
8395  حوار خاص مهندس سعودي نباتك فكره تهدف لزراعه مل...   
8396                 كريم تطلق خدمه اطلب اي شيء الجديده   
8397  تقرير اممي جديد يشير الي تاثير جاءحه فيروس كور...   
8398  فريق مشترك يتحقق اوضاع النساء والاطفال داخل قو...   

                                                Content  \
0     جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...   
1     تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...   
2     وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...   
3     نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...   
4     دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...   
...                                                 ...   
8394  قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...   
8395  بدات الفكره نعومه اظفاره عندما كان السابعه عمر...   
8396  اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...   
8397  وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...   
8398  تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...   

                                                   Link         Category  
0     https://ryadiybusiness.com/%d8%aa%d9%8a%d8%b1%...      ريادة أعمال  
1     https://ryadiybusiness.com/%d9%83%d9%8a%d9%81-...      ريادة أعمال  
2     https://arabic.sputniknews.com/science/2020100...  علوم وتكنولوجيا  
3     https://arabic.sputniknews.com/world/202012151...  علوم وتكنولوجيا  
4     https://arabic.rt.com//technology/1161864-%D8%...  علوم وتكنولوجيا  
...                                                 ...              ...  
8394  https://asharq.com/ar/7vNsbHVkd9fTQhBQI70ASx-ق...  علوم وتكنولوجيا  
8395       https://news.un.org/ar/story/2020/09/1062802             أخرى  
8396  https://ryadiybusiness.com/%d9%83%d8%b1%d9%8a%...      ريادة أعمال  
8397       https://news.un.org/ar/story/2020/06/1057232             أخرى  
8398       https://news.un.org/ar/story/2019/11/1043621             أخرى  

[8399 rows x 4 columns]

In [49]:
data.isnull().sum()

Title        0
Content     13
Link         0
Category     0
dtype: int64

In [50]:
data.Category.unique()

array(['ريادة أعمال', 'علوم وتكنولوجيا', 'أخرى'], dtype=object)

# Data Preprocessing

In [51]:
data.drop(["Title"] ,axis =1 ,inplace= True)
data.drop(["Link"] ,axis =1 ,inplace= True)
data.dropna(inplace = True)

In [52]:
data

Content         Category
0     جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...      ريادة أعمال
1     تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...      ريادة أعمال
2     وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...  علوم وتكنولوجيا
3     نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...  علوم وتكنولوجيا
4     دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...  علوم وتكنولوجيا
...                                                 ...              ...
8394  قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...  علوم وتكنولوجيا
8395  بدات الفكره نعومه اظفاره عندما كان السابعه عمر...             أخرى
8396  اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...      ريادة أعمال
8397  وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...             أخرى
8398  تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...             أخرى

[8386 rows x 2 columns]

In [53]:
#nltk.download('punkt')

In [54]:
le = LabelEncoder()

In [55]:
data['Category'] =le.fit_transform(data.Category)

In [56]:
data

Content  Category
0     جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...         1
1     تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...         1
2     وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...         2
3     نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...         2
4     دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...         2
...                                                 ...       ...
8394  قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...         2
8395  بدات الفكره نعومه اظفاره عندما كان السابعه عمر...         0
8396  اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...         1
8397  وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...         0
8398  تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...         0

[8386 rows x 2 columns]

# Data Normalization

In [57]:
#data['Content'] = data.Content.map(lambda x: x.lower())
#data['Content'] = data.Content.str.replace('[^\w\s]', '')

Tokenization

In [58]:
data['Content'] = data['Content'].apply(nltk.word_tokenize)

In [59]:
data['Content'][8396]

['اعلنت',
 'منصه',
 'كريم',
 '4',
 'فبراير',
 'الجاري',
 'اطلاق',
 'خدمه',
 'اطلب',
 'اي',
 'شيء',
 'الجديده',
 'الطلب',
 'دبي',
 'بهدف',
 'تطوير',
 'خدمه',
 '’',
 'كريم',
 'بوكسCareem',
 'Box',
 '‘',
 'السابقه',
 'لتتيح',
 'الان',
 'خدمات',
 'التوصيل',
 'الطلب',
 'وبموجب',
 'الخطوه',
 'يمكن',
 'للعملاء',
 'طلب',
 'واستلام',
 'كافه',
 'الطرود',
 'المرغوبه',
 'الاغراض',
 'الشخصيه',
 'ومنتجات',
 'التجزءه',
 'والتي',
 'تتسع',
 'ضمن',
 'صندوق',
 'بابعاد',
 '32',
 '32',
 '32',
 'وتزن',
 '7',
 'كغ',
 'كحد',
 'اقصيوتبدا',
 'اجور',
 'الخدمه',
 'الجديده',
 '8',
 'درهم',
 'اماراتي',
 'وتوفر',
 'خيارين',
 'الخدمات',
 'عبر',
 'تطبيق',
 '’',
 'Careem',
 'NOW',
 '‘',
 'خدمه',
 'الاستلام',
 'والتوصيل',
 'يقوم',
 'العاملون',
 'باستلام',
 'اي',
 'غرض',
 'منسي',
 'او',
 'طرد',
 'صديق',
 'وتوصيله',
 'للعميل',
 'وخدمه',
 'التسوق',
 'والتوصيل',
 'يقوم',
 'كابتن',
 'كريم',
 'بالتسوق',
 'نيابه',
 'العميل',
 'لشراء',
 'اغراض',
 'تتجاوز',
 'قيمتها',
 '350',
 'درهم',
 'اماراتيوتشكل',
 'خدمه',
 '’',
 'اطلب',
 'ا

Stemming

In [60]:
st = nltk.ISRIStemmer()
data['Content'] = data['Content'].apply(lambda x: [st.stem(y) for y in x])

In [61]:
data['Content'][8396]

['اعل',
 'نصه',
 'كرم',
 '4',
 'رير',
 'جري',
 'طلق',
 'خدم',
 'طلب',
 'اي',
 'شيء',
 'جدد',
 'طلب',
 'دبي',
 'هدف',
 'طور',
 'خدم',
 '’',
 'كرم',
 'بوكسCareem',
 'Box',
 '‘',
 'سبق',
 'تتح',
 'الن',
 'خدم',
 'وصل',
 'طلب',
 'وجب',
 'خطه',
 'يمكن',
 'عملاء',
 'طلب',
 'لام',
 'كفه',
 'طرد',
 'رغب',
 'غرض',
 'شخص',
 'نتج',
 'جزء',
 'والتي',
 'تسع',
 'ضمن',
 'صندوق',
 'بعد',
 '32',
 '32',
 '32',
 'وتز',
 '7',
 'كغ',
 'كحد',
 'اقصيوتبدا',
 'اجر',
 'خدم',
 'جدد',
 '8',
 'درهم',
 'مرا',
 'وفر',
 'خير',
 'خدم',
 'عبر',
 'طبق',
 '’',
 'Careem',
 'NOW',
 '‘',
 'خدم',
 'لام',
 'وصل',
 'يقم',
 'عمل',
 'لام',
 'اي',
 'غرض',
 'نسي',
 'او',
 'طرد',
 'صدق',
 'وصل',
 'عمل',
 'خدم',
 'تسق',
 'وصل',
 'يقم',
 'كاب',
 'كرم',
 'تسق',
 'نيب',
 'عمل',
 'شرء',
 'غرض',
 'جوز',
 'قيم',
 '350',
 'درهم',
 'اماراتيوتشكل',
 'خدم',
 '’',
 'طلب',
 'اي',
 'شيء',
 '‘',
 'جزء',
 'خطط',
 'رمي',
 'الي',
 'وفر',
 'بقه',
 'وسع',
 'خدم',
 'وصل',
 'طلب',
 'عملاء',
 'نتح',
 'لام',
 'وصل',
 'تسق',
 'احتياجات',
 'بمن',
 'سلس',
 

Join

In [62]:
data['Content'] = data['Content'].apply(lambda x: ' '.join(x))

# Feature Extraction

In [63]:
binary_enc = CountVectorizer(binary = True)
features = binary_enc.fit_transform(data['Content'])
#pd.DataFrame(features.toarray(), columns=tfidf_vect.vocabulary_.keys())

In [64]:
x_train,x_test ,y_train,y_test =train_test_split(features, data['Category'] ,test_size =.2 ,shuffle= False)

In [65]:
print(x_train.shape)
print(x_test.shape)

(6708, 83510)
(1678, 83510)


# Naive Bayes Model

In [66]:
model = MultinomialNB()

In [67]:
model.fit(x_train,y_train)

MultinomialNB()

In [68]:
predicted = model.predict(x_test)

In [69]:
print(np.mean(predicted == y_test))

0.9606674612634089


In [70]:
print(confusion_matrix(y_test,predicted))

[[536   5   5]
 [  4 552   5]
 [ 21  26 524]]
